package main

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckGeneratedHeaders(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "api", "gen", "good.pb.go"), "// Code generated by test. DO NOT EDIT.\npackage fixture\n")
	writeTestFile(t, filepath.Join(root, "migrations", "catalog_gen.go"), "package fixture\n")
	writeTestFile(t, filepath.Join(root, "outside_gen.go"), "// Code generated by test. DO NOT EDIT.\npackage fixture\n")

	if err := checkGeneratedHeaders(root, []string{filepath.Join("api", "gen", "good.pb.go")}); err != nil {
		t.Fatalf("valid generated header: %v", err)
	}
	if err := checkGeneratedHeaders(root, []string{filepath.Join("migrations", "catalog_gen.go")}); err == nil {
		t.Fatal("missing generated header was accepted")
	}
	if err := checkGeneratedHeaders(root, []string{"outside_gen.go"}); err == nil ||
		!strings.Contains(err.Error(), "outside a declared path") {
		t.Fatalf("generated path error = %v", err)
	}
}

func TestCheckMigrationNamesRejectsGapAndDuplicate(t *testing.T) {
	root := t.TempDir()
	migrationRoot := filepath.Join(root, "migrations")
	writeTestFile(t, filepath.Join(migrationRoot, "000000_bootstrap.sql"), "SELECT 1;\n")
	writeTestFile(t, filepath.Join(migrationRoot, "000002_gap.sql"), "SELECT 1;\n")
	if err := checkMigrationNames(root); err == nil || !strings.Contains(err.Error(), "contiguous") {
		t.Fatalf("migration gap error = %v, want contiguous-number failure", err)
	}

	if err := os.Remove(filepath.Join(migrationRoot, "000002_gap.sql")); err != nil {
		t.Fatalf("remove gap migration: %v", err)
	}
	writeTestFile(t, filepath.Join(migrationRoot, "000000_duplicate.sql"), "SELECT 1;\n")
	if err := checkMigrationNames(root); err == nil || !strings.Contains(err.Error(), "duplicated") {
		t.Fatalf("duplicate migration error = %v, want duplicate failure", err)
	}
}

func TestCheckNoTrackedDatabasesRejectsExtensionAndMagic(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "local.db"), "not sqlite")
	if err := checkNoTrackedDatabases(root, []string{"local.db"}); err == nil {
		t.Fatal("tracked database extension was accepted")
	}

	writeTestFile(t, filepath.Join(root, "disguised.bin"), "SQLite format 3\x00rest")
	if err := checkNoTrackedDatabases(root, []string{"disguised.bin"}); err == nil {
		t.Fatal("tracked SQLite magic was accepted")
	}
}

func TestCheckNoTrackedSecretsRejectsProviderKeyShape(t *testing.T) {
	root := t.TempDir()
	key := "sk-" + strings.Repeat("A", 24)
	writeTestFile(t, filepath.Join(root, "fixture.txt"), key)

	err := checkNoTrackedSecrets(root, []string{"fixture.txt"})
	if err == nil || !strings.Contains(err.Error(), "OpenAI API key") {
		t.Fatalf("secret scan error = %v, want OpenAI key classification", err)
	}
}

func TestCheckNoTrackedBrowserSourceRejectsAlternateFrontendStacks(t *testing.T) {
	for _, path := range []string{
		"web/client.js",
		"web/client.ts",
		"web/index.html",
		"web/shell.css",
	} {
		t.Run(filepath.Ext(path), func(t *testing.T) {
			err := checkNoTrackedBrowserSource([]string{path})
			if err == nil || !strings.Contains(err.Error(), "GoWebComponents v5") {
				t.Fatalf("browser-source error = %v, want GoWebComponents guidance", err)
			}
		})
	}
	if err := checkNoTrackedBrowserSource([]string{"web/client.go", "web/client.wasm"}); err != nil {
		t.Fatalf("Go/GWC outputs were rejected: %v", err)
	}
}

func TestCompareDirectoryTrees(t *testing.T) {
	expected := filepath.Join(t.TempDir(), "expected")
	actual := filepath.Join(t.TempDir(), "actual")
	writeTestFile(t, filepath.Join(expected, "a.go"), "same")
	writeTestFile(t, filepath.Join(actual, "a.go"), "same")
	if err := compareDirectoryTrees(expected, actual); err != nil {
		t.Fatalf("equal trees: %v", err)
	}
	writeTestFile(t, filepath.Join(actual, "a.go"), "changed")
	if err := compareDirectoryTrees(expected, actual); err == nil {
		t.Fatal("different generated trees were accepted")
	}
}

func TestRemoveArtifactChildRejectsArtifactRootAndExternalPath(t *testing.T) {
	root := t.TempDir()
	artifactRoot := filepath.Join(root, ".artifacts")
	if err := os.MkdirAll(filepath.Join(artifactRoot, "tmp", "child"), 0o755); err != nil {
		t.Fatalf("create artifact tree: %v", err)
	}
	if err := removeArtifactChild(root, artifactRoot); err == nil {
		t.Fatal("cleanup accepted .artifacts root")
	}
	if err := removeArtifactChild(root, filepath.Join(root, "source")); err == nil {
		t.Fatal("cleanup accepted external path")
	}
	child := filepath.Join(artifactRoot, "tmp", "child")
	if err := removeArtifactChild(root, child); err != nil {
		t.Fatalf("cleanup valid child: %v", err)
	}
	if _, err := os.Stat(child); !isNotExist(err) {
		t.Fatalf("artifact child still exists or stat failed unexpectedly: %v", err)
	}
}

func TestTrackedFilesUsesGitReviewBoundary(t *testing.T) {
	root := t.TempDir()
	command := func(args ...string) {
		t.Helper()
		if code := runCommandIn(context.Background(), root, os.Stdout, os.Stderr, "git", args...); code != exitSuccess {
			t.Fatalf("git %v failed", args)
		}
	}
	command("init")
	writeTestFile(t, filepath.Join(root, "tracked.txt"), "tracked")
	writeTestFile(t, filepath.Join(root, "untracked.txt"), "untracked")
	command("add", "--", "tracked.txt")

	files, err := trackedFiles(context.Background(), root)
	if err != nil {
		t.Fatalf("trackedFiles: %v", err)
	}
	if len(files) != 1 || files[0] != "tracked.txt" {
		t.Fatalf("trackedFiles = %v, want [tracked.txt]", files)
	}
}
