//go:build js && wasm

// Command renderfixture mounts real CodeFlux shell boundaries for browser
// render-isolation evidence. Its browser assets are generated by GWC.
package main

import (
	"fmt"
	"strconv"

	"codeflux.dev/codeflux/web/frontend/design"
	"codeflux.dev/codeflux/web/frontend/primitives"
	"codeflux.dev/codeflux/web/frontend/shell"
	"codeflux.dev/codeflux/web/frontend/state"
	"github.com/monstercameron/GoWebComponents/v5/fetch"
	"github.com/monstercameron/GoWebComponents/v5/html"
	"github.com/monstercameron/GoWebComponents/v5/ui"
	"github.com/monstercameron/GoWebComponents/v5/utils"
)

type reportingProbe struct{}

func (reportingProbe) Rendered(boundary string, revision uint64) {
	result := fetch.Fetch(
		"/render/"+boundary+"?revision="+strconv.FormatUint(revision, 10),
		fetch.Options{Method: "POST"},
	)
	go func() { <-result }()
}

func main() {
	ui.Render(ui.CreateElement(renderFixture), "#app")
	utils.WaitForever()
}

func renderFixture() ui.Node {
	probe := reportingProbe{}
	mode := primitives.Mode{
		Theme:   design.ThemeDark,
		Density: design.DensityComfortable,
	}
	return html.Main(html.Props{
		DataAttr: html.DataAttribute{Name: "testid", Value: "render-isolation-fixture"},
	},
		ui.CreateElement(costBoundary, boundaryProps{Mode: mode, Probe: probe}),
		ui.CreateElement(threadBoundary, boundaryProps{Mode: mode, Probe: probe}),
		ui.CreateElement(messageBoundary, boundaryProps{Mode: mode, Probe: probe}),
		ui.CreateElement(graphBoundary, boundaryProps{Mode: mode, Probe: probe}),
	)
}

type boundaryProps struct {
	Mode  primitives.Mode
	Probe shell.RenderProbe
}

func costBoundary(props boundaryProps) ui.Node {
	revision := ui.UseState(uint64(1))
	update := func() { revision.Update(func(current uint64) uint64 { return current + 1 }) }
	label := "$" + strconv.FormatUint(revision.Get(), 10) + ".00"
	return html.Section(html.Props{},
		html.Button(html.Props{
			Type: "button", Text: "Update cost",
			DataAttr: html.DataAttribute{Name: "testid", Value: "update-cost"},
			OnClick:  ui.WrapHandler(update),
		}),
		ui.CreateElement(shell.ApplicationBar, shell.ApplicationBarProps{
			Session: state.SessionView{
				Bootstrap:  state.BootstrapReady,
				Connection: state.ConnectionLive,
			},
			Workspace: state.WorkspaceView{
				RepositoryName: "codeflux", Branch: "main",
			},
			View: state.TopBarView{
				Repository: "codeflux", Branch: "main", TaskState: "running",
				Connection: state.ConnectionLive, Model: "gpt-5", Effort: "high",
				ForecastCost: label, ActualCost: label, HardBudget: "$4.00",
			},
			CostLabel: label,
			Revision:  revision.Get(),
			Mode:      props.Mode,
			Viewport:  state.ViewportWide,
			Probe:     props.Probe,
		}),
	)
}

func threadBoundary(props boundaryProps) ui.Node {
	return ui.CreateElement(shell.ThreadRail, shell.ThreadRailProps{
		State: state.DataReady,
		Threads: []state.ThreadView{
			{ID: "thread-1", Title: "Render isolation", Status: "active"},
		},
		SelectedID: "thread-1",
		Revision:   1,
		Mode:       props.Mode,
		Probe:      props.Probe,
	})
}

func messageBoundary(props boundaryProps) ui.Node {
	messages := ui.UseState([]state.MessageView{
		{ID: "message-1", Role: "requirement", Body: "Keep render ownership local.", Sequence: 1},
	})
	appendMessage := func() {
		messages.Update(func(current []state.MessageView) []state.MessageView {
			next := append([]state.MessageView(nil), current...)
			sequence := uint64(len(next) + 1)
			return append(next, state.MessageView{
				ID:       fmt.Sprintf("message-%d", sequence),
				Role:     "execution",
				Body:     "Mounted GWC append " + strconv.FormatUint(sequence, 10),
				Sequence: sequence,
			})
		})
	}
	return html.Section(html.Props{},
		html.Button(html.Props{
			Type: "button", Text: "Append message",
			DataAttr: html.DataAttribute{Name: "testid", Value: "append-message"},
			OnClick:  ui.WrapHandler(appendMessage),
		}),
		ui.CreateElement(shell.ConversationPane, shell.ConversationPaneProps{
			State:    state.DataReady,
			Messages: messages.Get(),
			Revision: uint64(len(messages.Get())),
			Mode:     props.Mode,
			Probe:    props.Probe,
		}),
	)
}

func graphBoundary(props boundaryProps) ui.Node {
	selected := ui.UseState("node-1")
	nodes := []state.GraphNodeView{
		{ID: "node-1", Title: "First node", Status: "complete"},
		{ID: "node-2", Title: "Second node", Status: "active"},
	}
	revision := uint64(1)
	if selected.Get() == "node-2" {
		revision = 2
	}
	return ui.CreateElement(shell.GraphPane, shell.GraphPaneProps{
		State:      state.DataReady,
		Nodes:      nodes,
		SelectedID: selected.Get(),
		Revision:   revision,
		Mode:       props.Mode,
		Probe:      props.Probe,
		OnSelect:   selected.Set,
	})
}
