// Code generated by codeflux-dev generate. DO NOT EDIT.
// Source: migrations/*.sql; generator schema: 1.

package migrations

var Catalog = []Descriptor{
	{Number: 0, Name: "000000_bootstrap.sql", SHA256: "1d7c1ae77ec211363c9054d5e587712db421087d76ad26cf27e0882b74d3a98d"},
	{Number: 1, Name: "000001_initial_operational_schema.sql", SHA256: "78f02ea4aae92c234f7257c0f4ada9e1c4007d4fe10d66c79eacb2b7d450ef9c"},
	{Number: 2, Name: "000002_settings_revisions.sql", SHA256: "1bbdf7dde934b679365aa11e8d5c636b47a1702db0715848e17f4d264e228fc0"},
	{Number: 3, Name: "000003_provider_credential_references.sql", SHA256: "a4dc7037c6300eadbf24335487ec53c41b20bb7987c673c4c4150e7976db3d78"},
	{Number: 4, Name: "000004_session_event_journal.sql", SHA256: "4ca6de4e74ac21e54e6d31e82e2d6463fe4c6629b091664ea9a0ff3d81cf1cb8"},
	{Number: 5, Name: "000005_context_manifests.sql", SHA256: "b9fd5e1eda91cdff1ee07222c6008c12410653a888b1c471aefa3a89b13fc3f8"},
	{Number: 6, Name: "000006_task_worktree_bindings.sql", SHA256: "b00ce44f5afb7a2653e44c63acb7ed1e3af068f61a4d343c6625b4168072f9ad"},
	{Number: 7, Name: "000007_tool_authority_and_commands.sql", SHA256: "2818b8b2aca5750dd76781b48edb9251ffb8d01f18c413e9731bb28a49fd377d"},
	{Number: 8, Name: "000008_worker_lifecycle.sql", SHA256: "c31caad6873e92338efc41ec2c6572b4d067a1b961abc051370f41acb5e95352"},
	{Number: 9, Name: "000009_provider_accounting.sql", SHA256: "7bb4e933d89784c070445ff8d6ec9730fb61ed49a42543c51333b9135ab9c404"},
	{Number: 10, Name: "000010_budget_ledger.sql", SHA256: "59ae538ea617c6f3a834b43632ba7efcb74cdf424c7258f2244a6811a030a6b6"},
	{Number: 11, Name: "000011_execution_preflight.sql", SHA256: "a510387c17234387c146afc8b09b53dfe7c4192f8a19a62aec85c4c04dac2e21"},
	{Number: 12, Name: "000012_preflight_budget_adjustments.sql", SHA256: "41e2233e67515413726b3e7e0b3bd9223ec9d2ea2848bea8f571fda26cb6d7b2"},
	{Number: 13, Name: "000013_provider_call_slot_reconciliation.sql", SHA256: "3b002da47edce72258223241cba0fd18e2507c7397ff309f1ec30345a470516e"},
}
