// Code generated by codeflux-dev generate. DO NOT EDIT.
// Source: migration catalog and frontend asset manifest; generator schema: 1.

package buildinfo

const generatedSchemaVersion uint32 = 25
const generatedFrontendVersion = "assets-e3b0c44298fc"
